#! /bin/sh
#
# A hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Redirect output to stderr.

original=/var/lib/sysv-rc-conf/services
copy=/etc/sysv-rc-conf-services

die() {
	echo "$*" >& 2
	false || exit
}

if cmp -s -- "$original" "$copy"
then
	:
else
	cat < "$original" > "$copy"
	die "$copy has been updated - consider committing it!" >& 2
fi

for h in /etc/git-hooks/*
do
	case $h in */README) continue; esac
	t=../../${h#/etc/}
	s=/etc/.git/hooks/${h#/etc/git-hooks/*}
	test -L "$s" || die "Symlink '$s' to '$t' does not exist!"
	test "`readlink -- "$s"`" = "$t" \
		|| die "Symlink '$s' does not point to '$t'!"
done
