# Assume an inactivity timeout of 2700 seconds (45 minutes) for all
# connections or packet destination routes through the current NAT gateway.
#
# v2026.135

ServerAliveInterval 2655
ServerAliveCountMax 1
