#! /bin/sh

# Switch the green ACT LED of the RPi4 to show mmc0 activity.
#
# v2025.25
set -e

case `grep ^Model /proc/cpuinfo` in
	*'Raspberry Pi '[34]*) ;;
	*) exit
esac

echo mmc0 > /sys/class/leds/ACT/trigger
