#! /bin/sh
tagfile_no_bootloader=/boot/bootcode.bin

text() {
	cat << 'EOF' | nl_extract "$@" \
	| iconv -f UTF-7 | fmt -cw 66 | iconv -t LATIN1
: r
Instructions for rebooting the machine:
: r L=de
Anweisungen zum Neustarten des Computers:
: p
Instructions for powering off the machine:
: p L=de
Anweisungen zum Abschalten des Computers:
: r pB pI

*
  First, press [Ctrl]+[Alt]+[F1] in order to switch to text console.
: r pB pI L=de

*
  Dr+APw-cken Sie als erstes +AFs-Strg+AF0AKwBb-Alt+AF0AKwBb-F1+AF0 um von der
  grafischen Oberfl+AOQ-che auf die Textkonsole zu wechseln.
: r pB pI

*
  In text console press [Ctrl]+[Alt]+[Del] in order to shut down and reboot
  the system.
: r pB pI L=de

*
  Dr+APw-cken Sie in der Textkonsole +AFs-Strg+AF0AKwBb-Alt+AF0AKwBb-Entf+AF0
  um den Computer herunter zu fahren und neu zu starten.
: pB

*
  As soon as the boot manager screen appears after reboot, stop the automatic
  countdown by selecting "Power Off" from the menu.
: pB L=de

*
  Sobald das Men+APw des Boot-Managers erscheint, brechen Sie den Countdown
  der Vorgabe-Men+APw-auswahl ab, und w+AOQ-hlen Sie statt dessen den Punkt
  +ACI-Power Off+ACI aus dem Men+APw.
: pB

*
  If you were too slow to stop the countdown and the Full-Disk Encryption
  password is prompted for already, press [Ctrl]+[Alt]+[SysRq]+[r] to reboot
  and try again.
: pB L=de

*
  Falls Sie zu langsam waren um den Countdown noch abbrechen zu k+APY-nnen und
  Sie bereits nach dem Passwort f+APw-r die Festplatten-Entschl+APw-sselung
  gefragt werden, dr+APw-cken Sie
  +AFs-Strg+AF0AKwBb-Alt+AF0AKwBb-SyReq+AF0AKwBb-r+AF0 f+APw-r einen
  sofortigen Neustart, nach welchem der Boot-Manager erneut sein Men+APw
  anzeigt und ihnen die Chance auf einen neuen Versuch zum Abbruch des
  Countdowns bietet.
: pI

*
  Wait for the reboot to happen and until the Full-Disk Encryption password is
  prompted for. Then press [Ctrl]+[Alt]+[SysRq]+[o] to power-off the machine
  instead of entering the password.
: pI L=de

*
  Warten Sie bis der Neustart abgeschlossen wurde und der Computer nach dem
  Passwort f+APw-r die Festplatten-Entschl+APw-sselung fragt. Anstatt das
  Passwort einzugeben, dr+APw-cken Sie jedoch
  +AFs-Strg+AF0AKwBb-Alt+AF0AKwBb-SyReq+AF0AKwBb-o+AF0 um den Computer
  abzuschalten.
EOF
}

nl_extract() {
	local lang t output line
	lang=$LC_ALL; : ${lang:=$LC_MESSAGES}; : ${lang:=$LANG}
	lang=${lang%.*}; lang=${lang%"@"*}
	if test -n "$lang"
	then
		set -- "$@" L="$lang"
		t=${lang%_*}
		test x"$t" != x"$lang" && test -n "$t" && set -- "$@" L="$t"
	fi
	output=false
	while IFS= read -r line
	do
		case $line in
			:*)
				case $line in
					*L=*) ;;
					*) line="$line L=en"
				esac
				if match "$line" "$@"
				then
					output=true
				else
					output=false
				fi
				;;
			*)
				if $output
				then
					printf '%s\n' "$line"
				fi
		esac
	done
}

match() {
	local rest tok t matched
	rest=${1#:}" "; shift
	matched=false
	for tok
	do
		t=${rest%" $tok "*}
		if test x"$t" != x"$rest"
		then
			case $tok in
				L=*) ;;
				*) matched=true
			esac
			rest=${rest#"$t $tok"}
			rest=$t$rest
		fi
	done
	test x"${rest% L=*}" = x"$rest" || return
	$matched || return
}

if test -e "$tagfile_no_bootloader"
then
	mod=I
else
	mod=B
fi
while :
do
	xmessage -buttons "Ausschalten,Neustarten" "$@" \
			"Alternative Aktionen" \
		&& rc=$? || rc=$?
	case $rc in
		101) text p$mod | xmessage -file - "$@";;
		102) text r | xmessage -file - "$@";;
		*) false || exit
	esac
done
