#!/bin/sh
#
# This script is run as root before showing login widget.

#xsetroot -solid rgb:8/8/8
if test -f /etc/default/locale
then
	. /etc/default/locale
	export LANG LANGUAGE
fi
/etc/X11/xdm/buttons -geometry -0-0 &
xclock -geometry +0-0 -digital -update 30 -strftime "%A %e. %B %Y %H:%M" \
	-face "Times New Roman-24" &
