#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
# 
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

# Wait for $TIMEOUT_SECONDS before continuing. This shall be run before
# dropbear is stopped, in order to avoid this happening immediately after
# mounting the real root filesystem (not that of the initramfs).

TIMEOUT_SECONDS=90

set -e

PREREQS='dropbear'

case $1 in
	prereqs) echo "$PREREQS"; exit
esac

. /scripts/functions

what='r/o-mount root filesystem'
log_success_msg "Waiting for timeout in order to $what"
sleep $TIMEOUT_SECONDS
log_success_msg "Continuing boot sequence - prepare to $what"
