# Configure ModemManager to ignore modem devices marked by UDEV rules as
#
# ENV{ID_MM_DEVICE_IGNORE}="1"
#
# Such modem devices must then be managed manually by /etc/ppp/peers/*,
# pon/poff, ifup/ifdown and chatscripts or similar means.
#
# If you want ModemManager to automatically controll all modem devices,
# you do not need to install this configuration file.
#
# v2026.139

[general]
FilterPolicy=STRICT
