# Enforce that NetworkManager does not control any Ethernet or WWAN devices
# (such as a modem).
#
# This makes sense if you have an existing legacy configuration using
# ifup/ifdown and do not want NetworkManager to screw it all up.
#
# Do *not* install this configuration file if you want NetworkManager to
# control all network devices automatically.
#
# v2026.139

[main]
plugins=keyfile

[keyfile]
unmanaged-devices=type:ethernet;type:wwan
