#! /bin/sh
# Version 2021.317
#
# Refresh the single archive on /boot where all the modules for all the
# installed kernels are present. This allows the same module archive file to
# be used by all kernels.
#
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

KERNEL_VERSION=${1:?kernel version}
bb=busybox-pbyqxzl1ktqlk3fjm3arlrclg # Optional.
bb_fallback=busybox # Optional.
pp=pipe_progress # Optional.
strip='/usr/bin/*linux*-strip'
strip_opts=-g

retry() {
	tries=5
	until "$@" 2> /dev/null
	do
		tries=`expr $tries - 1` || exit
		sleep 1
	done
}

set -e
cleanup() {
	rc=$?
	test "$OUTFILE" && rm -- "$OUTFILE"
	test "$RMTRO" && retry mount -o remount,ro /boot
	test "$TD" && rm -r -- "$TD"
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
RMTRO=
TD=
OUTFILE=
trap cleanup 0
trap 'exit $?' INT HUP TERM QUIT

have() {
	command -v "$1" > /dev/null 2>& 1 || return
}

not() {
	if "$@"
	then
		false || return
	fi
	:
}

if not have "$pp"
then
	have "$bb" || bb=$bb_fallback
	if have "$bb" && "$bb" --list 2> /dev/null | grep -q -- "$pp"
	then
		pp="$bb $pp"
	else
		pp=cat
	fi
fi
arc=xz
tarext=$arc
have "$arc"
arc="$arc -c"

m=/proc/meminfo
test -e "$m"
m=`awk '$1 == "MemTotal:" && $3 == "kB" {print $2}' "$m"`
c=9
test $m -lt 1000000 && c=8
arc=$arc$c

if test ! -w /boot
then
	mount -o remount,rw /boot
	RMTRO=yes
fi
outfile=/boot/modules.$tarext


TD=`mktemp -d -- "${TMPDIR:-/tmp}/${0##*/}".XXXXXXXXXX`
chmod 700 "$TD"
echo "Stripping copies of kernel modules"
(
	cd -- "$TD"
	cp -pr /lib/modules/* .
	find -name '*.ko' | $pp | {
		set -- $strip
		test $# -ge 1
		for s
		do
			test -x "$s"
		done
		while read m
		do
			tries=$#
			while :
			do
				if
					case $tries in
						1) "$1" $strip_opts "$m";;
						*)
							"$1" $strip_opts "$m" \
								>& 5 2>& 5
					esac
				then
					break
				fi
				set -- "$@" "$1"; shift
				tries=`expr $tries - 1` || exit
			done
		done 5> /dev/null
	}
)

if test `find "$TD" -name '*.ko' | wc -l` = 0
then
	if test -e "$outfile"
	then
		a=Deleting
		OUTFILE=$outfile
		echo "$a $OUTFILE"
	fi
	exit
fi

a=Creating
test -e "$outfile" && a=Refreshing
> "$outfile" # Might save needed space.
OUTFILE=$outfile
echo "$a $OUTFILE"
(
	cd -- "$TD" && find * | LC_COLLATE=C sort | cpio -oH newc
) | $arc | $pp > "$OUTFILE"
OUTFILE=
