#! /bin/sh

# v2025.252
set -e

case $1 in
	prereqs) echo utilities-k5487f9fqve065q5y0wfhfue3; exit
esac

. /usr/share/initramfs-tools/hook-functions

while IFS= read -r module
do
	manual_add_modules "$module"
done <<- 'EOF'
	aes_x86_64
	algif_skcipher
	des_generic
	dm_crypt
	sd_mod
	serpent
	serpent_sse2_x86_64
	sha512_generic
	xts
EOF

copy_exec /usr/bin/find /bin/gfind
copy_exec /usr/bin/tput /bin/
ln -sn ../lib/cryptsetup/askpass "$DESTDIR"/bin/
unset tinfos
#{{terminfo-4ayq79y9zk95hdtevtfjcqphr
# v2025.252
: {tinfos:=linux}
tidst=${DESTDIR}/etc/terminfo
for ti in $tinfos
do
	tidir=${ti#?} && tidir=${ti%$tidir} || exit
	for tibase in /usr/share/terminfo /lib/terminfo
	do
		tifile=$tibase/$tidir/$ti
		test -f "$tifile" && break
	done
	if test ! -d "$tidst/$tidir"
	then
		mkdir -p -- "$tidst/$tidir" || exit
	fi
	cp -- "$tifile" "$tidst/$tidir"/ || exit
done
unset tinfos tidst ti tifile tidir tibase
#terminfo-4ayq79y9zk95hdtevtfjcqphr}}
