#! /bin/sh
set -e

case $1 in
	prereqs) echo utilities-k5487f9fqve065q5y0wfhfue3; exit
esac

. /usr/share/initramfs-tools/hook-functions

while IFS= read -r module
do
	manual_add_modules "$module"
done <<- 'EOF'
	aes_x86_64
	algif_skcipher
	des_generic
	dm_crypt
	sd_mod
	serpent
	serpent_sse2_x86_64
	sha512_generic
	xts
EOF

copy_exec /usr/bin/find /bin/gfind
copy_exec /usr/bin/tput /bin/
ln -sn ../lib/cryptsetup/askpass "$DESTDIR"/bin/
mkdir -p "$DESTDIR"/etc/terminfo/l
cp /lib/terminfo/l/linux "$DESTDIR"/etc/terminfo/l/
