#! /bin/sh
# Version 2021.364
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

PREREQS='locale-j2mkmlcr0gu1pkjv7vn84ksnl'

set -e

case $1 in
	prereqs) echo "$PREREQS"; exit
esac
