#! /bin/sh
# Version 2021.363
#
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e

case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

have() {
	result=`command -v $1 2> /dev/null` || return
}

cpe() {
	copy_exec "$1" "${1%/*}"
}

for fs in ext2 ext3 ext4
do
	if have fsck.$fs
	then
		cpe "$result"
		have mkfs.$fs
		cpe "$result"
		manual_add_modules $fs
	fi
done
for u in tune2fs resize2fs
do
	have $u
	cpe "$result"
done
for c in /etc/e2*.conf
do
	test ! -e "$c" && continue
	cp "$c" "$DESTDIR"/etc/
done
