#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

# Install fdisk, which is necessary for re-partitioning the disks from
# within initfamfs.

utility=/sbin/fdisk

set -e

case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

d=$DESTDIR$utility
test -e "$d" && rm -- "$d"

copy_exec "$utility" "${utility%/*}"/
