#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

# Install GNU tar, which (other than BusyBox tar) supports also EAs and ACLs,
# which is necessary for copying modern filesystem contents and its metadata
# completely.

tar=/bin/tar

set -e

case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

d=$DESTDIR$tar
test -e "$d" && rm -- "$d"

"$tar" --version | grep -q GNU
copy_exec "$tar" "${tar%/*}"/
