#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

DEFAULTS=/etc/default/rng-tools

set -e

case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

for tool in rngd
do
	for dir in /usr/sbin /usr/bin /sbin /bin
	do
		path=$dir/$tool
		if test -f "$path"
		then
			copy_exec "$path" "$dir"/
			continue 2
		fi
	done
	echo "$tool not found!" >& 2; false || exit
done

test -f "$DEFAULTS" || DEFAULTS=/dev/null

RUN_CONF=$DESTDIR/conf/conf.d/hwrng-le2e77uym5ybexyl2ah6mhmix
mkdir -p -- `dirname -- "$RUN_CONF"`
grep ^DAEMON_ARGS= "$DEFAULTS" > "$RUN_CONF" || :

# haveged places the PID file in /var/run, which should be a symlink to /run
# (which will have been mounted as its own tmpfs).
vr=$DESTDIR/var/run
tgt=../run
while
		test ! -e "$vr" \
	||	test "`readlink -- "$vr"`" != "$tgt"
do
	if test -d "$vr"
	then
		rmdir "$vr"
	elif test -L "$vr"
	then
		rm "$vr"
	elif test -e "$vr"
	then
		echo "initramfs /var/run is neither a directory" \
			"nor a symlink!" >& 2
		false || exit
	fi
	mkdir -p "`dirname -- "$vr"`"
	ln -s "$tgt" "$vr"
done
