#! /bin/sh
# Version 2023.166
# Copyright (c) 2018-2023 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

ti_src=/lib/terminfo
ti_dst=/etc/terminfo
tinfos='linux screen xterm'

set -e
locale=`locale -a | grep -iE '^C[.]UTF[[:punct:]]*8$'`
test "$locale"
locale_data=/usr/lib/locale/$locale

case $1 in
	prereqs) echo; exit
esac

test "$verbose" != n && echo "Installing $locale locale" >& 2
find -H "$locale_data" \
| while IFS= read -r fso
do
	dest=$DESTDIR$fso
	if test -d "$fso"
	then
		mode=`stat -c %a -- "$fso"`
		mkdir -pm "$mode" -- "$dest"
	else
		cp -Pp -- "$fso" "$dest"
	fi
done
