#! /bin/sh
# Version 2018.211
#
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e
case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

# The Debian initramfs uses a non-POSIX compliant "tr" which does not support
# character classes. Our scripts need that feature, so install the
# full-fledged utility rather than that stripped down version. BTW: BusyBox
# "tr" *does* support character classes! But obviously Debian has disabled it
# when building "to save space".
rm -- "$DESTDIR"/bin/tr
copy_exec /usr/bin/tr /bin/
