#! /bin/sh

# v2023.142
#
# Update reference to $INITRD in $BOOTCFG, making the kernel use the new
# initrd after the next reboot. The target version is taken from $version.
BOOTLDR_DIR=/boot
BOOTCFG=$BOOTLDR_DIR/config.txt

case $1 in
	prereqs) echo; exit
esac

set -e
cleanup() {
	rc=$?
	test "$T" && rm -- "$T"
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
T=
trap cleanup 0
trap 'exit $?' INT QUIT TERM HUP

test "$version"
npfx=`expr x"$version" : x'\(\([1-9][0-9]*\.\)*[1-9][0-9]*\)'`
nsfx=${version#"$npfx"}
T=`mktemp -- ${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX`

orx=' *initramfs \{1,\}initrd\.img-\([-.0-9a-z]\{1,\}+\) \{1,\}'`:
	`'followkernel *$'
while IFS= read -r line
do
	ov=`expr x"$line" : x"$orx"` \
	&& test "$ov" \
	&& opfx=`expr x"$ov" : x'\(\([1-9][0-9]*\.\)*[1-9][0-9]*\)'` \
	&& osfx=${ov#"$opfx"} \
	&& test "$nsfx" = "$osfx" \
	&& echo "initramfs initrd.img-$npfx$osfx followkernel" \
	|| printf '%s\n' "$line"
done < "$BOOTCFG" > "$T"

# Update file only if necessary.
if ! cmp -s -- "$BOOTCFG" "$T"
then
	cat < "$T" > "$BOOTCFG"
fi
