#! /bin/sh
# Version 2021.363
#
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e

case $1 in
	prereqs) echo; exit
esac

. /usr/share/initramfs-tools/hook-functions

have() {
	result=`command -v $1 2> /dev/null` || return
}

cpe() {
	copy_exec "$1" "${1%/*}"
}

manual_add_modules vfat

for u in fsck.vfat mkfs.vfat dosfslabel
do
	have $u
	cpe "$result"
done
