#! /bin/sh
# Version 2021.297
#
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

KERNEL_VERSION=$1

set -e
trap 'test $? = 0 || echo "\"$0\" failed!" >& 2' 0


test -w /boot && ro=false || ro=true
case $ro in
	true) mount -o remount,rw /boot
esac

rm -f -- /boot/modules-"$KERNEL_VERSION.txz"

case $ro in
	true) mount -o remount,ro /boot
esac
