#! /bin/sh

# Version 2025.171
# Copyright (c) 2021-2025 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

KERNEL_VERSION=${1:?kernel version}
target=/boot/firmware
target_fallback=/boot

test -d "$target" || target=$target_fallback

retry() {
	tries=5
	until "$@" 2> /dev/null
	do
		tries=`expr $tries - 1` || exit
		sleep 1
	done
}

set -e
cleanup() {
	rc=$?
	test "$RMTRO" && retry mount -o remount,ro "$target"
	test $rc = 0 || echo "\"$0\" failed!" >& 2
}
RMTRO=
trap cleanup 0
trap 'exit $?' INT HUP TERM QUIT

a=xz
tarext=t$a
MODARCH=$target/modules-$KERNEL_VERSION.$tarext

test ! -e "$MODARCH" && exit

if test ! -w "$target"
then
	mount -o remount,rw "$target"
	RMTRO=yes
fi

rm -- "$MODARCH"
