#! /bin/sh

# v2025.252
where=/root
tagfile=bin/true

set -e
while test ! -e "$where/$tagfile"
do
	echo
	echo "Please be so good and read-only mount the REAL filesystem"
	echo "root on $where!"
	echo
	echo "If '/usr' happens to be a filesystem separate from '/',"
	echo "then please read-only mount '/usr' as well."
	echo
	echo "Then enter 'exit' to continue booting."
	ash
	sleep 1
done
echo
echo "Thank you so very much! Continuing boot process."
echo
