# This snippet is grouped into blocks. The order between the blocks should not
# be changed. The lines within each block is sorted lexicographically, except
# for commments which always come first.

# Associate networks with domain names.
domain=ethbvm.emgenxx69lwyn5ctlr4nl64ul.local,10.20.0.0/16,local
domain=eth.emgenxx69lwyn5ctlr4nl64ul.local,10.48.0.0/16,local
domain=vm.emgenxx69lwyn5ctlr4nl64ul.local,10.176.0.0/16,local
domain=wifi.emgenxx69lwyn5ctlr4nl64ul.local,10.222.0.0/16,local

# Define DHCP ranges within networks and assign range aliases.
dhcp-range=set:bvm,10.20.223.250,10.20.255.254,infinite
dhcp-range=set:eth,10.48.223.250,10.48.255.254,infinite
dhcp-range=set:vm,10.176.223.250,10.176.255.254,infinite
dhcp-range=set:wifi,10.222.223.250,10.222.255.254,infinite

# Associate range aliases with domain names.
dhcp-option=tag:bvm,option:domain-name,ethbvm.emgenxx69lwyn5ctlr4nl64ul.local
dhcp-option=tag:eth,option:domain-name,eth.emgenxx69lwyn5ctlr4nl64ul.local
dhcp-option=tag:vm,option:domain-name,vm.emgenxx69lwyn5ctlr4nl64ul.local
dhcp-option=tag:wifi,option:domain-name,wifi.emgenxx69lwyn5ctlr4nl64ul.local
