#! /bin/sh
# Implicitly remove any "use-ssh-agent" from "/etc/X11/Xsession.options".

# Version 2019.255
# Copyright (c) 2019 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

OPTIONS=`printf '%s' "$OPTIONS" | grep -vFx use-ssh-agent`
