#! /bin/sh
# Helper for /etc/crypttab.
#
# v2022.8.1

set -e
test "$CRYPTTAB_OPTION_keyscript" = "$0"

exec /etc/libexec/cached/keygen-octets-by-harvesting-entropy \
	`expr "$CRYPTTAB_OPTION_size" / 8`
