#! /bin/sh
# Warning: This script only works with either GNU or BusyBox "ls"!
#
# And even the output formats of those two are different (but will both work
# with this script).
#
# Version 2021.45
# Copyright (c) 2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

ls --version 2>& 1 | grep -Eq 'BusyBox|GNU' || exit
find /etc -name .git -prune -o -path /etc \
	-o -exec ls --full-time -lcd -- {} + \
| LC_COLLATE=C sort -k 9
