#! /bin/sh
# This script will be called by patched scripts as
#
# $ exec /etc/libexec/update-patch-5cj2dtd975yp5yah4ku3ll4ia "$0" "$ofile" "$@"
#
# where
#
# $ofile: Name of the unmodified original version of $0.
#
# THIS script shall do the following:
#
# * Canonicalize path names of $0 and $ofile before further processing.
# * Copy file $ofile to $0.
# * Apply patch $PATCHES_BASE/$0.patch (see below).
# * Write result of "stat -c %i+%Z $ofile" to $UPDATE_KEYS/$0 (see below).
# * Re-exec "$0" "$@".
#
# Version 2020.62
# Copyright (c) 2020 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

# Keep the following values in sync with ./update-patch-helper-5cj2dtd975yp5yah4ku3ll4ia!
HYPE_NAME=diversion-patches
UUID=5cj2dtd975yp5yah4ku3ll4ia
PATCHES_REL_BASE=../$HYPE_NAME-$UUID
UPDATE_KEYS=/var/lib/$HYPE_NAME-$UUID

set -e
inform() {
	# Log to stderr if stdin is a terminal, or to syslog otherwise.
	# Daemons usually redirect their standard input from /dev/null.
	local level
	level=$1; shift
	if test -t 0
	then
		printf '%s\n' "$*" >& 2
	else
		logger -t "$APP" -p user.$level -- "$*"
	fi
}
complain() {
	inform warning "$@"
}
APP=${0##*/}
trap 'test $? = 0 || complain "$0 failed!"' 0

PATCHES_BASE=`dirname -- "$0"`/$PATCHES_REL_BASE

# Sets $path to absolute canonicalized path name for command $1.
mk_absx() {
	local paths p
	path=$1
	case $path in
		/*) ;;
		*/*) false || exit;;
		*)
			# Locate $path in a directory from $PATH.
			paths=$PATH:
			while :
			do
				p=${paths%%:*}
				paths=${paths#*:}
				case $p in
					/*)
						p=${p%%/}/$path
						if
							test -f "$p" \
							&& test -x "$p"
						then
							path=$p
							break
						fi
				esac
				test -n "$paths" # Otherwise: Not found.
			done
	esac
	test -e "$path"
	path=`readlink -f -- "$path"`
	test -f "$path"; test -x "$path"
}

orig_name=$1; mk_absx "$orig_name"; ufile=$path
mk_absx "$2"; ofile=$path
shift 2

patch=$PATCHES_BASE/$ufile.patch
test -f "$patch"
tfile=$ufile.$APP.tmp
> "$tfile"
chmod 600 -- "$tfile"
cat < "$ofile" > "$tfile"
patch -i "$patch" -- "$tfile" > /dev/null 2>& 1 || {
	rm -- "$tfile"
	complain "Could not patch '$ufile' based on '$ofile'"
	complain "by applying patch '$patch'!"
	complain "Please apply the patch manually. Then regenerate the patch."
	false || exit
}
cat < "$tfile" > "$ufile"
rm -- "$tfile"
inform notice "Patch for updated '$ufile' has been re-applied successfully"

ukeyloc=$UPDATE_KEYS/$ufile
ukeydir=`dirname -- "$ukeyloc"`
test -d "$ukeydir" || mkdir -p -- "$ukeydir"
stat -c %i+%Z -- "$ofile" > "$ukeyloc"

exec "$orig_name" "$@"
