#! /bin/sh
# Version 2021.363
#
# Copyright (c) 2018-2021 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e

# For start/stop
DAEMON=/usr/sbin/rngd
NAME=rngd
PIDFILE=/var/run/rngd.pid
SETTINGS=/conf/conf.d/hwrng-le2e77uym5ybexyl2ah6mhmix

case $1 in
	prereqs) echo; exit
esac

if test -e "$SETTINGS"
then
	. "$SETTINGS"
fi
. /scripts/functions

log_begin_msg "Stopping hardware random daemon"
if
	start-stop-daemon --stop --quiet --pidfile $PIDFILE \
		--startas $DAEMON --retry 10 --name $NAME \
		> /dev/null 2>& 1
then
	:
else
	if start-stop-daemon --test $START > /dev/null 2>& 1
	then
		:
	else
		false || exit
	fi
	rm -- "$PIDFILE"
fi
log_end_msg
