#! /bin/sh

# v2026.34
prereqs() {
	# Make sure that cryptroot is run last in local-top.
	for req in `dirname $0`/*
	do
		script=${req##*/}
		if test $script != cryptroot-1z88d0bny63a5wzph7r1wdxla
		then
			echo $script
		fi
	done
}

case $1 in
	prereqs) prereqs; exit
esac

# source for log_*_msg() functions, see LP: #272301
. /scripts/functions

fallback() {
	log_failure_msg "Mount the cryptoroot manually, umount any /tmp, then 'exit'!"
	exec ash
}

trap fallback 0
set -e

# Avoid mapping multiple times if already executed successfully once.
if test ! -e /dev/mapper/$mapping
then
	if
		command -v manual_crypto_unlock-3cx4bfsxqgkyu30ffdzuim0hx \
			> /dev/null 2>& 1
	then
		manual_crypto_unlock-3cx4bfsxqgkyu30ffdzuim0hx $mapping
	else
		cryptsetup-bm1fu35d94e5tbvvfib9bzgi0 $mapping
	fi
fi
trap - 0
