#! /bin/sh
# Yes I know the name of this script is a bit idiotic, but it should run after
# "wpasupplicant" and the scripts in this directory are not numbered and have
# no other way to express execution order than by choosing their names.
#
# Of course, I could have called it zzz_something, but who knows which other
# packages might drop scripts in here, and this script does not necessarily
# have to be run after *all* of them.

set -e

what=wifi
state_file=/var/run/rfkill-$what-holders

test $PHASE = post-down || exit 0

case $IFACE in
	$what* | wlan*) ;;
	*) exit 0
esac

rfkill=`which rfkill 2> /dev/null` || exit 0

(
	flock -n 9 || exit
	T=`mktemp "${TMPDIR:-/tmp}/${0##*/}.XXXXXXXXXX"`
	trap 'rm -- "$T"' 0
	while IFS= read -r ifc
	do
		test x"$ifc" != x"$IFACE" && printf '%s\n' "$ifc"
	done < "$state_file" > "$T"
	cat "$T" > "$state_file"
	if test ! -s "$state_file"
	then
		# No holders any more.
		rfkill block $what
	fi
) 9>> "$state_file"
