#! /bin/sh
# v2020.351
ARCHIVE=/tmp/ppp-cap.gz
LOG_GROUP=adm
LOG_MODE=640
LIVE=/tmp/ppp-live-cap
OPT_HELPER=/etc/libexec/ringbuffer_file

test ! -e "$LIVE" && exit

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

uok() {
	test `find "$1" -uid 0 -type f 2> /dev/null | wc -l` = 1
}

sperm() {
	chgrp "$LOG_GROUP" -- "$1"
	chmod "$LOG_MODE" -- "$1"
}

if uok "$ARCHIVE"
then
	:
else
	rm -f -- "$ARCHIVE"
	> "$ARCHIVE"
fi
sperm "$ARCHIVE"

if uok "$LIVE"
then
	gzip -c9 < "$LIVE" | {
		if test -x "$OPT_HELPER"
		then
			{
				# Separation prefix.
				printf %s '<0bstssl1dejjaluwmv1y2jpsh>'
				cat
			} | "$OPT_HELPER" "$ARCHIVE"
		else
			cat >> "$ARCHIVE"
		fi
	}
fi
> "$LIVE"
