#! /bin/sh
ARCHIVE=/tmp/ppp-cap.gz
LOG_GROUP=adm
LOG_MODE=640
LIVE=/tmp/ppp-live-cap

test ! -e "$ARCHIVE" && test ! -e "$LIVE" && exit

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

uok() {
	test `find "$1" -uid 0 -type f 2> /dev/null | wc -l` = 1
}

sperm() {
	chgrp "$LOG_GROUP" -- "$1"
	chmod "$LOG_MODE" -- "$1"
}

if uok "$LIVE"
then
	sperm "$LIVE"
	sperm "$LIVE" # In case there has been a race condition.
fi

test ! -e "$LIVE" && exit

uok "$ARCHIVE" || { true; exit; }

test ! -s "$ARCHIVE" || sperm "$ARCHIVE"

if test -e "$LIVE" && uok "$LIVE"
then
	gzip -c9 < "$LIVE" >> "$ARCHIVE"
fi
> "$LIVE"
