#! /bin/sh
ARCHIVE=/tmp/ppp-cap.gz
LOG_GROUP=adm
LOG_MODE=600
LIVE=/tmp/ppp-live-cap

test ! -e "$ARCHIVE" && exit

set -e
trap 'test $? = 0 || echo "$0 failed!" >& 2' 0

uok() {
	test `find "$1" -uid 0 -type f 2> /dev/null | wc -l` = 1
}

uok "$ARCHIVE" || { true; exit; }

sperm() {
	chgrp "$LOG_GROUP" -- "$1"
	chmod "$LOG_MODE" -- "$1"
}

test ! -s "$ARCHIVE" || sperm "$ARCHIVE"

if test -e "$LIVE" && uok "$LIVE"
then
	gzip -c9 < "$LIVE" >> "$ARCHIVE"
	> "$LIVE"
else
	> "$LIVE"
	sperm "$LIVE"
fi
