#! /bin/sh
# Version 2022.8
#
# Copyright (c) 2022 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

PREREQS="udev"

set -e

case $1 in
	prereqs) echo "$PREREQS"; exit
esac

. /scripts/functions

cd /dev
ln -s ../proc/self/fd .
ln -s fd/0 stdin
ln -s fd/1 stdout
ln -s fd/2 stderr
