#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

# Replace /dev/urandom by a copy of /dev/random in order to avoid
# "uninitialized urandom read" messages in the kernel log. This is especially
# important if dropbear is used. Make sure haveged will be running, so that
# the new /dev/urandom will not block for long when running out of entropy
# temporarily.
UR=/dev/urandom
MAJOR=1
WANT_MINOR=8 # like /dev/random
MODE=666
PREREQS=haveged-qny2b5f0vg7c2b5n07kv5zqkf

set -e
case $1 in
	prereqs) echo "$PREREQS"; exit
esac

. /scripts/functions

test -c $UR && test "`stat -c %T $UR`" = $WANT_MINOR && exit

log_begin_msg "Enforcing entropy for urandom"
PATH=$PATH:/sbin:/usr/sbin
if test -e $UR
then
	bu=$UR.orig
	if test -e $bu
	then
		rm $UR
	else
		mv $UR $bu
	fi
fi
mknod -m 666 $UR c $MAJOR $WANT_MINOR
log_end_msg
