#! /bin/sh
# Copyright (c) 2018 Guenther Brunthaler. All rights reserved.
#
# This script is free software.
# Distribution is permitted under the terms of the GPLv3.

set -e

# For start/stop
DAEMON=/usr/sbin/rngd
NAME=rngd
PIDFILE=/var/run/rngd.pid
SETTINGS=/conf/conf.d/hwrng-le2e77uym5ybexyl2ah6mhmix

# For starting.
RNGDOPTIONS=
HRNGDEVICE=/dev/hwrng
DEVICELIST="hwrng hw_random hwrandom intel_rng i810_rng"

case $1 in
	prereqs) echo; exit
esac

. "$SETTINGS"
. /scripts/functions


finddevice () {
	test -c "$HRNGDEVICE" && return
	for i in $DEVICELIST
	 do
		if test -c "/dev/$i"
		then
			HRNGDEVICE=/dev/$i
			return
		fi
		if test -c "/dev/misc/$i"
		then
			HRNGDEVICE="/dev/misc/$i"
			return
		fi
	done
	echo "(Hardware RNG device inode not found)"
	echo "$0: Cannot find a hardware RNG device to use." >&2
	false || exit
}


log_begin_msg "Starting hardware random daemon"
PATH=$PATH:/sbin:/usr/sbin
finddevice
START="--start --quiet --pidfile $PIDFILE --startas $DAEMON --name $NAME"
START="$START -- -r $HRNGDEVICE $RNGDOPTIONS"
if start-stop-daemon $START > /dev/null 2>& 1
then
	:
else
	if start-stop-daemon --test $START > /dev/null 2>& 1
	then
		false || exit 1
	fi
fi
while test ! -f "$PIDFILE"
do
	sleep 1
done
log_end_msg
