#! /bin/sh

# Dummy script. I have no idea what it is used for. But I know that
# initramfs gets caught in an infinite loop if it is missing when trying
# to get a rescue shell. So we provide this script, as useless as it is.
#
# v2025.308
