#! /bin/sh
### BEGIN INIT INFO
# Provides:          lifetime_writes
# Required-Start:    $local_fs $time
# Required-Stop:     $local_fs
# Default-Start:     S
# Default-Stop:      0 6
# Short-Description: Save bytes written counters to files.
# Description:       This script saves the counters of bytes written to
#                    devices between restarts.
### END INIT INFO

# v2021.301

NAME=lifetime_writes
DESC="record amount of data ever written to configured mass storage"
DEFAULTSFILE="/etc/default/$NAME"

# Set defaults

lifetime_logger=/etc/cron.daily/lifetime-writes-sc7km47ls0fx7d0aijdqtn91v

# Allow overriding defaults via configuration file, if any.
test -r "$DEFAULTSFILE" && . "$DEFAULTSFILE"

test -r "$lifetime_logger" || exit

. /lib/init/vars.sh
. /lib/lsb/init-functions

case $1 in
  stop)
	test "$VERBOSE" = no \
		|| log_action_begin_msg "Saving disk-written counters"
	"$lifetime_logger"; es=$?
	test "$VERBOSE" = no || log_action_end_msg $es
	;;
  status | start | "")
	exit
	;;
  restart | reload | force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  *)
	echo "Usage: $0 start | stop" >&2
	exit 3
	;;
esac

:
